# Generated by Django 4.2.1 on 2023-05-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
